### ISSUE TITLE
Multiple contexts

### ISSUE THREAD

**Issue by FelipeCavichiolliSilvestre** [devyuji/utilisetime#3]
I saw that you use multiple contexts, one for each method, and that's not really necessary.
This is how context.tsx would look like:
```typescript
interface DataContextProps {
  data: Data[];
  totalTime: Time;
  addData: (value: Data) => null;
  deleteData: (index: number, time: string) => null;
  updateTime: (value: Time) => null;
}

export const DataContext = createContext({
  data: initalValue.data,
  totalTime: initalValue.totalTime,
  addData: () => null,
  deleteData: () => null,
  updateTime: () => null,
} as DataContextProps);

const ContextProvider: FC = ({ children }) => {
  // All of the code in context remain unchanged expect by return.

  return (
    <DataContext.Provider
      value={{ data, totalTime, addData, deleteData, updateTime }}
    >
      {children}
    </DataContext.Provider>
  );
};

// create a hook alias for useContext(DataContext)
export const useData = () => useContext(DataContext);
```

In the components:
```typescript
  // before
  const addData = useContext(AddContext);

  const totalTime = useContext(TotalTimeContext);

  const updateTime = useContext(UpdateTimeContext);

  // after
  const { addData, totalTime, updateTime } = useData();
```

**Comment by devyuji** [comment]
> I saw that you use multiple contexts, one for each method, and that's not really necessary.
> This is how context.tsx would look like:
> ```typescript
> interface DataContextProps {
>   data: Data[];
>   totalTime: Time;
>   addData: (value: Data) => null;
>   deleteData: (index: number, time: string) => null;
>   updateTime: (value: Time) => null;
> }
> 
> export const DataContext = createContext({
>   data: initalValue.data,
>   totalTime: initalValue.totalTime,
>   addData: () => null,
>   deleteData: () => null,
>   updateTime: () => null,
> } as DataContextProps);
> 
> const ContextProvider: FC = ({ children }) => {
>   // All of the code in context remain unchanged expect by return.
> 
>   return (
>     <DataContext.Provider
>       value={{ data, totalTime, addData, deleteData, updateTime }}
>     >
>       {children}
>     </DataContext.Provider>
>   );
> };
> 
> // create a hook alias for useContext(DataContext)
> export const useData = () => useContext(DataContext);
> ```
> 
> In the components:
> ```typescript
>   // before
>   const addData = useContext(AddContext);
> 
>   const totalTime = useContext(TotalTimeContext);
> 
>   const updateTime = useContext(UpdateTimeContext);
> 
>   // after
>   const { addData, totalTime, updateTime } = useData();
> ```
> 

Thanks for the feedback. 😀
